export const ADD_TO_ORDER="ADD_TO_ORDER";
export const UPDATE_ORDER="UPDATE_ORDER";
export const DELETE_FROM_ORDER="DELETE_FROM_ORDER";
export const DELETE_ALL_ORDER="DELETE_ALL_ORDER";
export const CHANGE_CURRENCY="CHANGE_CURRENCY";

export const CHANGE_VISIBILITY_CART="CHANGE_VISIBILITY_CART";
export const CHANGE_VISIBILITY_LOGIN="CHANGE_VISIBILITY_LOGIN";